name: CloudFormation Deployment

on:
  push:
    jobs:
      build:
        runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name creationstack \
            --template-file .github/workflows/S3creation.yaml \
            --capabilities CAPABILITY_NAMED_IAM

            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
              AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
